# This workflow will release and publish the project with Maven
# It uses Maven release to release the process including deploy.
# Deployment is done to GitHub Package registry.

name: Maven Release

on:
  push:

jobs:
  release:
    name: Maven Release

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets. GH_RELEASE_TOKEN }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[
        { "id": "github", "name": "GitHub zetool Apache Maven Packages", "url": "https://maven.pkg.github.com/zetool/rndutils" }
        ]'
        servers: '[{ "id": "github", "username": "zetool-bot", "password": "${GITHUB_TOKEN}" }]'
    - name: Build with Maven
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: mvn -B package --file pom.xml
